"use client";

import {
  Users,
  UserCheck,
  UserPlus,
  DollarSign,
} from "lucide-react";

import {
  Card,
  CardContent,
} from "@/components/ui/card";

import { mockMembers } from "./MockMembers";

export default function NetworkMetricCards() {
  const totalMembers = mockMembers.length;

  const activeMembers = mockMembers.filter(
    (member) => member.status === "Active"
  ).length;

  const pendingMembers = mockMembers.filter(
    (member) => member.status === "Pending"
  ).length;

  const totalRevenue = mockMembers.reduce(
    (sum, member) => sum + member.revenueGenerated,
    0
  );

  const metrics = [
    {
      title: "Total Members",
      value: totalMembers.toLocaleString(),
      subtitle: "Across your network",
      icon: Users,
      iconBg: "bg-blue-100",
      iconColor: "text-blue-600",
    },
    {
      title: "Active Members",
      value: activeMembers.toLocaleString(),
      subtitle: `${Math.round(
        (activeMembers / totalMembers) * 100
      )}% currently active`,
      icon: UserCheck,
      iconBg: "bg-emerald-100",
      iconColor: "text-emerald-600",
    },
    {
      title: "Pending Invites",
      value: pendingMembers.toLocaleString(),
      subtitle: "Awaiting acceptance",
      icon: UserPlus,
      iconBg: "bg-amber-100",
      iconColor: "text-amber-600",
    },
    {
      title: "Revenue Managed",
      value: `$${totalRevenue.toLocaleString()}`,
      subtitle: "Generated by members",
      icon: DollarSign,
      iconBg: "bg-violet-100",
      iconColor: "text-violet-600",
    },
  ];

  return (
    <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
      {metrics.map((metric) => {
        const Icon = metric.icon;

        return (
          <Card
            key={metric.title}
            className="rounded-3xl border shadow-sm transition-shadow hover:shadow-md"
          >
            <CardContent className="flex items-start justify-between p-6">
              <div>
                <p className="text-sm font-medium text-muted-foreground">
                  {metric.title}
                </p>

                <h2 className="mt-3 text-3xl font-bold tracking-tight">
                  {metric.value}
                </h2>

                <p className="mt-2 text-sm text-muted-foreground">
                  {metric.subtitle}
                </p>
              </div>

              <div
                className={`flex h-14 w-14 items-center justify-center rounded-2xl ${metric.iconBg}`}
              >
                <Icon
                  className={`h-7 w-7 ${metric.iconColor}`}
                />
              </div>
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}