"use client";

import {
  Users,
  UserCheck,
  UserPlus,
  DollarSign,
} from "lucide-react";

import {
  Card,
  CardContent,
} from "@/components/ui/card";

import { Skeleton } from "@/components/ui/skeleton";

export interface NetworkMetrics {
  totalMembers: number;
  activeMembers: number;
  pendingMembers: number;
  totalRevenue: number;
}

interface NetworkMetricCardsProps {
  data?: NetworkMetrics | null;
  loading?: boolean;
}

const metricsConfig = [
  {
    title: "Total Members",
    subtitle: "Across your network",
    icon: Users,
    iconBg: "bg-blue-100",
    iconColor: "text-blue-600",
  },
  {
    title: "Active Members",
    subtitle: "currently active",
    icon: UserCheck,
    iconBg: "bg-emerald-100",
    iconColor: "text-emerald-600",
  },
  {
    title: "Pending Invites",
    subtitle: "Awaiting acceptance",
    icon: UserPlus,
    iconBg: "bg-amber-100",
    iconColor: "text-amber-600",
  },
  {
    title: "Revenue Managed",
    subtitle: "Generated by members",
    icon: DollarSign,
    iconBg: "bg-violet-100",
    iconColor: "text-violet-600",
  },
];

function MetricSkeleton() {
  return (
    <Card className="rounded-3xl border shadow-sm">
      <CardContent className="flex items-start justify-between p-6">
        <div className="space-y-3">
          <Skeleton className="h-4 w-28" />
          <Skeleton className="h-9 w-24" />
          <Skeleton className="h-4 w-36" />
        </div>

        <Skeleton className="h-14 w-14 rounded-2xl" />
      </CardContent>
    </Card>
  );
}

export default function NetworkMetricCards({
  data = null,
  loading = false,
}: NetworkMetricCardsProps) {
  if (loading) {
    return (
      <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
        {Array.from({ length: 4 }).map((_, index) => (
          <MetricSkeleton key={index} />
        ))}
      </div>
    );
  }

  const totalMembers = data?.totalMembers ?? 0;
  const activeMembers = data?.activeMembers ?? 0;
  const pendingMembers = data?.pendingMembers ?? 0;
  const totalRevenue = data?.totalRevenue ?? 0;

  const activePercentage =
    totalMembers > 0
      ? Math.round((activeMembers / totalMembers) * 100)
      : 0;

  const values = [
    {
      value: totalMembers.toLocaleString(),
      subtitle: "Across your network",
    },
    {
      value: activeMembers.toLocaleString(),
      subtitle: `${activePercentage}% currently active`,
    },
    {
      value: pendingMembers.toLocaleString(),
      subtitle: "Awaiting acceptance",
    },
    {
      value: `₦${totalRevenue.toLocaleString()}`,
      subtitle: "Generated by members",
    },
  ];

  return (
    <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
      {metricsConfig.map((metric, index) => {
        const Icon = metric.icon;
        const item = values[index];

        return (
          <Card
            key={metric.title}
            className="rounded-3xl border shadow-sm transition-shadow hover:shadow-md"
          >
            <CardContent className="flex items-start justify-between p-6">
              <div>
                <p className="text-sm font-medium text-muted-foreground">
                  {metric.title}
                </p>

                <h2 className="mt-3 text-3xl font-bold tracking-tight">
                  {item.value}
                </h2>

                <p className="mt-2 text-sm text-muted-foreground">
                  {item.subtitle}
                </p>
              </div>

              <div
                className={`flex h-14 w-14 items-center justify-center rounded-2xl ${metric.iconBg}`}
              >
                <Icon
                  className={`h-7 w-7 ${metric.iconColor}`}
                />
              </div>
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}
